apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-adapter
data:
  config.yaml: |
    rules:
      - seriesQuery: 'job:scaletestapp_requests_per_second:rate1m'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "job:scaletestapp_requests_per_second:rate1m"
          as: "scaletestapp_requests_per_second"
        metricsQuery: 'job:scaletestapp_requests_per_second:rate1m{<<.LabelMatchers>>}'
