@startuml
!include C4_Container.puml

Person(mobile, "Mobile App", "Покупатель использует мобильное приложение")
Container_Boundary(nm, "NovaMarket Platform") {
    Container(api, "NGINX API Gateway", "Nginx / Ingress", "Маршрутизация запросов, TLS termination, rate limiting")
}

Container(kafka, "Event Broker", "Kafka Cluster", "Event-driven взаимодействие между всеми сервисами")

Container_Boundary(auth_boundary, "Auth Domain") {
    Container(auth, "Auth Service", "Python + Postgres", "Регистрация, аутентификация, управление методами оплаты")
    ContainerDb(authhDB, "Database", "PostgreSQL", "Данные о пользователях")
}

Container_Boundary(seller_boundary, "Seller Domain") {
    Container(seller, "Seller Service", "Python + Postgres", "Управление продавцами")
    ContainerDb(sellerDB, "Database", "PostgreSQL", "Данные о продавцах")
}

Container_Boundary(catalog_boundary, "Catalog Domain") {
    Container(catalog, "Catalog Service", "Python + Postgres/ElasticSearch", "Товары, описание, категории")
    ContainerDb(catalogDB, "Database", "PostgreSQL", "Данные о товарах")
}


Container_Boundary(cart_boundary, "Cart Domain") {
    Container(cart, "Cart Service", "Python + Redis", "Корзина пользователя, временное хранилище")
    ContainerDb(cartDB, "Database", "Redis", "Данные о корзине")
}

Container_Boundary(order_boundary, "Order Domain") {
    Container(order, "Order Service", "Python + Postgres", "Создание заказа")
    ContainerDb(orderDB, "Database", "PostgreSQL", "Данные о заказах")
}

Container_Boundary(payment_boundary, "Payment Domain") {
    Container(payment, "Payment Service", "Python + Postgres", "Интеграция с платёжным шлюзом, обработка статусов платежей")
    ContainerDb(paymentDB, "Database", "PostgreSQL", "Данные о платежах")
}

Container_Boundary(inventory_boundary, "Inventory Domain") {
    Container(inventory, "Inventory Service", "Python + Postgres", "Остатки на складах, резервирование товаров")
    ContainerDb(inventoryDB, "Database", "PostgreSQL", "Данные об остатках на складе")
}

Container_Boundary(shipping_boundary, "Shipping Domain") {
    Container(shipping, "Shipping Service", "Python", "Интеграция со службой доставки, получение треков и статусов")
    ContainerDb(shippingDB, "Database", "PostgreSQL", "Данные о доставках")
}

Container_Boundary(notification_boundary, "Notification Domain") {
    Container(notification, "Notification Service", "Python", "Отправка push/email")
    ContainerDb(notificationDB, "Database", "PostgreSQL", "Данные об уведомлениях")
}


Container_Boundary(reviews_boundary, "Reviews Domain") {
    Container(reviews, "Reviews Service", "Python + Postgres", "Отзывы на товары")
    ContainerDb(reviewsDB, "Database", "PostgreSQL", "Данные об отзывах на товары")
}


Rel(mobile, api, "HTTP/REST")
Rel(api, auth_boundary, "JWT auth / user ops")
Rel(api, catalog, "Просмотр каталога")
Rel(api, reviews, "Просмотр отзывов на товары")
Rel(api, cart, "Работа с корзиной")
Rel(api, kafka, "Создание и управление заказами")
Rel(api, seller, "Управление продавцами")

Rel(payment, kafka, "PaymentSucceeded / PaymentFailed (events)")
Rel(shipping, kafka, "ShipmentStatusUpdated (event)")


Rel(kafka, order, "OrderCreated, OrderConfirmed, OrderCancelled")
Rel(kafka, payment, "PaymentInitiated / Payment events")
Rel(kafka, inventory, "InventoryReserved / Failed / Released")
Rel(kafka, shipping, "Shipment events")
Rel(kafka, notification, "Send notifications")

Rel(auth, authhDB, "SQL")
Rel(catalog, catalogDB, "SQL")
Rel(cart, cartDB, "SQL")
Rel(reviews, reviewsDB, "SQL")
Rel(seller, sellerDB, "SQL")


Rel(order, orderDB, "SQL")
Rel(payment, paymentDB, "SQL")
Rel(inventory, inventoryDB, "SQL")
Rel(shipping, shippingDB, "SQL")
Rel(notification, notificationDB, "SQL")

@enduml
